/**
 * Known product categories (generated from the seeded dataset).
 * Lowercased to match the stored `category` field and the values Gemini
 * is allowed to return. Regenerate via dataset/gen_categories.py.
 */
export const KNOWN_CATEGORIES: string[] = [
  'acrylic sheet',
  'adathodai',
  'ads makeup',
  'air blower',
  'air freshener',
  'ajwa dates',
  'ajwain',
  'alfalfa hay',
  'almond milk',
  'aloe vera gel',
  'aloe vera juice',
  'alum',
  'aluminum foil',
  'anklet',
  'ant repellent',
  'antacid',
  'anti tick spray',
  'antiseptic',
  'apple',
  'aquarium light',
  'aquarium plants',
  'aquarium pump',
  'aquarium supplies',
  'arshakuthar',
  'artificial sweetener',
  'asafoetida',
  'ashwagandha',
  'ayurvedic churna',
  'ayurvedic herbs',
  'ayurvedic syrup',
  'ayurvedic tablet',
  'ayurvedic tailam',
  'ayurvedic tonic',
  'baby bath sponge',
  'baby bath support',
  'baby bath toy',
  'baby bathrobe',
  'baby bathtub',
  'baby bedding set',
  'baby bib',
  'baby bottle cleaner',
  'baby bowl set',
  'baby braider',
  'baby changing mat',
  'baby comb set',
  'baby crib toy',
  'baby cup feeder',
  'baby dress',
  'baby duck toy',
  'baby feeding nipple',
  'baby feeding set',
  'baby finger brush',
  'baby food',
  'baby formula',
  'baby gift set',
  'baby grooming',
  'baby hair clip',
  'baby hair clutcher',
  'baby hammer toy',
  'baby head band',
  'baby head protector',
  'baby headband',
  'baby knee pad',
  'baby lotion',
  'baby massage oil',
  'baby medicine dropper',
  'baby milestone cards',
  'baby mirror toy',
  'baby nail clipper',
  'baby nappy',
  'baby nibbler',
  'baby nipple',
  'baby oral tube',
  'baby pants',
  'baby pillow',
  'baby porridge',
  'baby potty',
  'baby potty seat',
  'baby potty stool',
  'baby powder',
  'baby rocker',
  'baby romper',
  'baby rubber sheet',
  'baby safety',
  'baby safety guard',
  'baby safety spoon',
  'baby shampoo',
  'baby shoes',
  'baby shower cap',
  'baby sign',
  'baby sipper',
  'baby snack container',
  'baby snacks',
  'baby soap',
  'baby spoon',
  'baby spoon set',
  'baby squeeze toy',
  'baby straw cup',
  'baby suction plate',
  'baby tableware',
  'baby teether',
  'baby towel',
  'baby toys',
  'baby washcloth',
  'baby wipes',
  'backpack',
  'bajra flour',
  'banana',
  'band aid',
  'bat mukti',
  'bathroom cleaner',
  'beard trimmer',
  'beauty balm',
  'beauty combo',
  'besan',
  'betel nut',
  'bindi',
  'bio oil',
  'bird cage perch',
  'bird supplies',
  'bird toy',
  'biscuits',
  'black pepper',
  'bleach',
  'blood pressure monitor',
  'blush',
  'body lotion',
  'body shake',
  'bonton tablet',
  'boys formal set',
  'brahmi ghrita',
  'bread',
  'breakfast cereal',
  'breast pump',
  'bronzer',
  'broom',
  'building blocks',
  'butter',
  'caffeine supplement',
  'cake',
  'calcium supplement',
  'camphor',
  'candy',
  'cardamom',
  'cat food',
  'cat litter',
  'cat tree',
  'chana dal',
  'channa sattu',
  'chat puri',
  'cheese',
  'chestnut',
  'chewing gum',
  'chicken',
  'chickpeas',
  'chikki',
  'chilla mix',
  'chilli sauce',
  'chimney cleaner',
  'chips',
  'chocolate',
  'chocolate bar',
  'choline',
  'chutney',
  'chyawanprash',
  'cigarette alternative',
  'cinnamon',
  'cla supplement',
  'cleaning brush',
  'cleansol',
  'clove',
  'coconut oil',
  'coconut pooja',
  'coconut water',
  'coffee',
  'cold medicine',
  'color corrector',
  'coloressence',
  'compact powder',
  'compound',
  'concealer brush',
  'concealer palette',
  'conditioner',
  'contact lens',
  'contour palette',
  'cooking oil',
  'coriander powder',
  'corn triangles',
  'corner protector',
  'cornflakes',
  'cosmetic bag',
  'cotton',
  'cranberries',
  'cream',
  'cumin',
  'cup noodles',
  'curd',
  'curry mix',
  'dairy whitener',
  'daliya',
  'deepam',
  'degreaser',
  'deodorant',
  'derma color',
  'dessert mix',
  'detergent',
  'detox supplement',
  'diabetic supplement',
  'diaper bin',
  'diapers',
  'diet supplement',
  'digestive candy',
  'digestive syrup',
  'dishwash',
  'dishwash bar',
  'disinfectant',
  'dog ball',
  'dog bone',
  'dog food',
  'dog frisbee',
  'dog harness',
  'dog muzzle',
  'dog prong collar',
  'dog t-shirt',
  'dog treats',
  'dr beckmann',
  'drain cleaner',
  'dried berries',
  'dried fruits',
  'dried vegetables',
  'dry clean wipes',
  'dry coconut',
  'duster',
  'ear plugs',
  'earpick',
  'eggs',
  'electric shaver',
  'enema kit',
  'energy bar',
  'energy drinks',
  'epilator',
  'essential oil',
  'evil eye',
  'eye care supplement',
  'eye drops ayurvedic',
  'eye liner',
  'eye patch',
  'eye shadow palette',
  'eyebrow pencil',
  'eyebrow stamp',
  'eyebrow stencil',
  'eyelash',
  'eyelash curler',
  'eyeshadow pigment',
  'eyeshadow shield',
  'eyewear',
  'fabric stiffener',
  'face cleaning cloth',
  'face cream',
  'face lotion',
  'face mask',
  'face primer',
  'face serum',
  'face wash',
  'facial bowl',
  'facial brush',
  'facial glitter',
  'facial kit',
  'facial wipes',
  'fat burner',
  'feeding bottle',
  'fenugreek',
  'fidget toys',
  'fish',
  'fish food',
  'fitness mix',
  'flavoured milk',
  'flax seeds',
  'floor cleaner',
  'follihair',
  'food color',
  'food container',
  'foot cream',
  'foot massager',
  'foot scrub',
  'foundation',
  'frankincense',
  'frozen snacks',
  'fruit crush',
  'fruit drink',
  'fruit juice',
  'furniture polish',
  'garbage bags',
  'garcinia supplement',
  'garlic',
  'ghee',
  'ginger',
  'girls dress',
  'glass cleaner',
  'glucometer',
  'glucosamine',
  'gluten free flour',
  'grape squash',
  'grapes',
  'green chilli',
  'grooming kit',
  'guinea pig food',
  'hair accessories',
  'hair band',
  'hair brush',
  'hair clipper',
  'hair color',
  'hair color men',
  'hair comb',
  'hair curler',
  'hair dryer',
  'hair extension',
  'hair lotion',
  'hair mask',
  'hair oil',
  'hair pack',
  'hair remover',
  'hair serum',
  'hair straightener',
  'hair wax',
  'hand wash',
  'hangover relief',
  'hard wax',
  'harem pants',
  'haritaki',
  'health drinks',
  'health supplement',
  'heating pad',
  'highlighter palette',
  'homeopathic globules',
  'homeopathy',
  'honey',
  'ice',
  'ice cream',
  'indian sweets',
  'indomie',
  'ink cup',
  'insect killer',
  'isopropyl alcohol',
  'jaggery',
  'jam',
  'jatamansi',
  'jaundex',
  'jawline exerciser',
  'jelly',
  'kajal',
  'karela supplement',
  'kayakalp oil',
  'kelp',
  'keratase hair care',
  'ketchup',
  'khakhra',
  'khichdi mix',
  'kimchi noodles',
  'kirayata',
  'kitchen roll',
  'kitchen towel',
  'lassi',
  'lemonade',
  'lip balm',
  'lip care',
  'lip crayon',
  'lip gloss',
  'lip liner',
  'lip tint',
  'lipstick',
  'liquid detergent',
  'liquid lipstick',
  'liver tonic',
  'loacker',
  'macadamia nuts',
  'magnesium supplement',
  'majoon',
  'makeup brush',
  'makeup brush set',
  'makeup kit',
  'makeup mirror',
  'makeup palette',
  'makeup remover',
  'makeup sponge',
  'makeup stick',
  'makeup wax',
  'manchurian mix',
  'mango',
  'mascara',
  'masoor',
  'masoor dal',
  'massager',
  'maternity bra',
  'maternity kurti',
  'matte lipstick',
  'mayonnaise',
  'mehendi',
  'mens delay spray',
  'menstrual cup',
  'menthol crystal',
  'metal polish',
  'milk',
  'millet',
  'mints',
  'miscellaneous',
  'miss rose',
  'mixed berries',
  'mixed spices',
  'moisturizer',
  'mood drops',
  'moong dal',
  'mop',
  'mosquito repellent',
  'mother sparsh',
  'mouth freshener',
  'mouthwash',
  'muesli',
  'multi cleaner',
  'multigrain flour',
  'muslin napkin',
  'mustard oil',
  'mustard oil hair',
  'mutton',
  'nac supplement',
  'nail clipper',
  'nail polish',
  'nail polish remover',
  'namkeen',
  'napkin rash cream',
  'neem leaf',
  'non-alcoholic wine',
  'noodles',
  'nozzle',
  'nursing cover',
  'nursing pad',
  'nutella',
  'nutritious bar',
  'nuts',
  'oat milk',
  'oats',
  'olay',
  'olive oil',
  'omega-3',
  'onion',
  'orange',
  'oregano',
  'organic dal',
  'orthopedic support',
  'pacifier',
  'pain relief',
  'paneer',
  'panipuri',
  'papad',
  'pasta',
  'peanut butter',
  'peanut snack',
  'peanuts',
  'pecan nuts',
  'peedanil',
  'peeling solution',
  'peonies',
  'pepper spray',
  'perfume',
  'perfume men',
  'period panties',
  'pest repellent',
  'pet bed',
  'pet blanket',
  'pet bowl',
  'pet cage',
  'pet calcium',
  'pet chew toy',
  'pet clothing',
  'pet collar',
  'pet grooming',
  'pet grooming tool',
  'pet hair remover',
  'pet leash',
  'pet potty',
  'pet rake comb',
  'pet saffa',
  'pet shampoo',
  'pet socks',
  'pet supplement',
  'pet toys',
  'pet training pad',
  'pet treats',
  'phenyl',
  'pickle',
  'pine nuts',
  'playpen',
  'poha',
  'popcorn',
  'potato',
  'prawns',
  'pre workout',
  'primer',
  'primer makeup',
  'probiotic',
  'prohance',
  'protein supplement',
  'prunes',
  'psyllium husk',
  'pudding',
  'puff pastry snacks',
  'puffed snacks',
  'pulses',
  'pumpkin seeds',
  'rabbit food',
  'ragi flour',
  'raisins',
  'rasam mix',
  'rava',
  'razor',
  'ready to eat meals',
  'ready-to-cook meals',
  'ready-to-fry snacks',
  'red chilli',
  'refill powder',
  'rice',
  'rose petals',
  'rose water',
  'rusk',
  'rust remover',
  'safflower oil',
  'saffron',
  'salt',
  'sandwich cracker',
  'sanitary pads',
  'sanitizer',
  'sarpagandha',
  'sciatic pain relief',
  'scrubber',
  'seasoning mix',
  'seasoning powder',
  'seeds',
  'sesame oil',
  'shampoo',
  'sharbat',
  'shatavari',
  'shaving cream',
  'shilajit',
  'sindoor',
  'skin protector',
  'sleep aid',
  'sleep mask',
  'snack bar',
  'snack bars',
  'soap',
  'socket cover',
  'soft drinks',
  'soft toy',
  'soy milk',
  'soy products',
  'soy sauce',
  'soya chunks',
  'soya products',
  'spinal brace',
  'sponge wipe',
  'spray cleaner',
  'squash & syrup',
  'squeaky ball',
  'squeegee',
  'stain remover',
  'steel shaker',
  'sugar',
  'suma',
  'sundri sudha',
  'sunflower oil',
  'sunscreen',
  'sunscreen gel',
  'supari',
  'surface cleaner',
  'surface wipes',
  'sushi nori',
  'swarna bhasma',
  'swarna guggulu',
  'syrup',
  'tableware',
  'taco shells',
  'talcum powder',
  'tampons',
  'tankan bhasma',
  'tap',
  'tartaric acid',
  'tattoo ink',
  'tattoo marker',
  'tattoo needle',
  'tattoo stencil',
  'tattoo supplies',
  'tea',
  'tempura flour',
  'thermometer',
  'tikhur',
  'tilasmi moti',
  'tissue',
  'toilet bowl cleaner',
  'toilet cleaner',
  'toilet paper',
  'toilet seat cover',
  'tomato',
  'tongue cleaner',
  'toor dal',
  'toothbrush',
  'toothpaste',
  'toy car',
  'training cup',
  'tribulus',
  'triphala',
  'truffle',
  'turmeric',
  'turtle food',
  'tutti frutti',
  'tweezers',
  'urad dal',
  'uric acid supplement',
  'vacuum cleaner',
  'varicose supplement',
  'vet supplement',
  'vinegar',
  'vitamins',
  'vooki cleaner',
  'wafers',
  'wall sticker',
  'wallet',
  'water',
  'wax strip',
  'wax warmer',
  'weight loss patch',
  'wet n wild',
  'wheat flour',
  'wheat gluten',
  'white peas',
  'window cleaner brush',
  'yeast',
  'yo yo',
  'yoga pants',
  'zeodary root',
  'zip lock bags',
];

/** Fast membership lookup. */
export const KNOWN_CATEGORY_SET = new Set(KNOWN_CATEGORIES);
